### ISSUE TITLE
Release of latest version (0.9) with Nil support in PartialDeserializer

### ISSUE THREAD

**Issue by yaelbrookes** [debasishg/scala-redis-nb#117]

**Comment by debasishg** [comment]
Hello - I don't have any bandwidth at this moment to work on the fix for Nil. Do you have a PR for this ? I can then merge it and do the release ..

Thanks.

**Comment by yaelbrookes** [comment]
Sorry, I wasn't clear - 
The fix has already been merged (https://github.com/debasishg/scala-redis-nb/pull/114), it's just that a release wasn't created after that. Could you please make the release? Thanks.

**Comment by debasishg** [comment]
done .. possibly will take some time for sync with Maven Central ..

**Comment by yaelbrookes** [comment]
Thanks!
